services:
  influxdb:
    container_name: rsyslog_influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    networks:
      - rsyslog_net
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=GOLDENBYTE
      - DOCKER_INFLUXDB_INIT_BUCKET=GOLDENBYTE-BUCKET
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=veryverysecuretoken
    volumes:
      - 'influxdb_data:/var/lib/influxdb'
    restart: always
  
  telegraf:
    container_name: rsyslog_telegraf
    image: telegraf:latest
    networks:
      - rsyslog_net
    environment:
      - INFLUXDB_TOKEN=veryverysecuretoken
    depends_on:
      - influxdb
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always

  rsyslog:
    container_name: rsyslog
    image: rsyslog/syslog_appliance_alpine
    networks:
      - rsyslog_net
    depends_on: 
      - telegraf
    ports:
      - 514:514/udp
    volumes:
      - ./conf/rsyslog/rsyslog.conf:/etc/rsyslog.conf:ro
      - config:/config
      - logs:/logs
    restart: always

volumes:
  config: {}
  logs: {}
  influxdb_data: {}

networks:
  rsyslog_net:
    driver: bridge

